version: '2'
services:
  newoapp3-app:
    image: newoapp3
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://newoapp3-postgresql:5432/NewoApp3
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://newoapp3-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://newoapp3-elasticsearch:9200
    ports:
      - 8080:8080
  newoapp3-postgresql:
    extends:
      file: postgresql.yml
      service: newoapp3-postgresql
  newoapp3-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: newoapp3-elasticsearch
